---
include:
  - board: nice_nano/nrf52840/zmk
    shield: wayfinder_left
  - board: nice_nano/nrf52840/zmk
    shield: wayfinder_right nice_view_custom
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
